CREATE DATABASE agenda_consulta;

USE agenda_consulta;

CREATE TABLE paciente(
id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(100) NOT null,
cpf VARCHAR(20) UNIQUE NOT NULL,
telefone VARCHAR(20),
senha VARCHAR(255) NOT NULL
);

ALTER TABLE paciente
MODIFY COLUMN id INT UNSIGNED AUTO_INCREMENT;

CREATE TABLE medico(
id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(100) NOT NULL,
crm VARCHAR(20) UNIQUE NOT NULL,
especialidade VARCHAR(100),
senha VARCHAR(255) NOT null
);

CREATE TABLE consulta(
id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
paciente_id INT UNSIGNED NOT NULL,
medico_id INT UNSIGNED NOT NULL,
data_hora DATETIME NOT NULL,
status ENUM('agendada', 'realizada', 'concluída') NOT NULL DEFAULT 'agendada', descricao TEXT,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
update_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
FOREIGN KEY (paciente_id) REFERENCES paciente(id) ON DELETE CASCADE,
FOREIGN KEY (medico_id) REFERENCES medico(id) ON DELETE CASCADE,
UNIQUE (medico_id, data_hora)
);

ALTER TABLE consulta
CHANGE COLUMN update_at updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
CHANGE COLUMN STATUS status ENUM('agendada', 'realizada', 'concluida') NOT NULL DEFAULT 'agendada';